// Everything on the site that is derived rather than authored: the SEO block
// in each page's <head>, one static page per published film, the 404 page,
// the pre-rendered film grid, sitemap.xml and robots.txt. Rebuilt after every
// content change so none of it can drift from the text and films it comes from.
import fs from "node:fs";
import path from "node:path";
import { HTML_PAGES, type PageFile } from "../config.ts";
import { readPortfolio, type Film, type Portfolio } from "./films.ts";
import { readSite, sitePath, siteExists, writeSite } from "./files.ts";
import { readSettings } from "./settings.ts";
import { readStrings, type Strings } from "./strings.ts";

const SITE_NAME = "On the Move Productions";
const EMAIL = "info@onthemove.cz";
const DEFAULT_SHARE_IMAGE = { path: "assets/img/hero-social.jpg", w: 1600, h: 900 };
const FILM_DIR = "work";

const esc = (s: unknown) =>
  String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const jsonLd = (data: unknown) => JSON.stringify(data).replace(/</g, "\\u003c");

function writeIfChanged(rel: string, content: string) {
  if (siteExists(rel) && readSite(rel) === content) return;
  writeSite(rel, content, { backup: false });
}

type Ctx = { strings: Strings; data: Portfolio; siteUrl: string; published: Film[] };

const abs = (ctx: Ctx, rel: string) => (ctx.siteUrl ? ctx.siteUrl + rel.replace(/^\.?\//, "") : rel);
const t = (ctx: Ctx, key: string, lang: "cs" | "en" = "cs") => ctx.strings[lang][key] ?? ctx.strings.cs[key] ?? "";
const catName = (ctx: Ctx, id: string, lang: "cs" | "en" = "cs") => ctx.data.categories.find((c) => c.id === id)?.name[lang] ?? "";
const filmTitle = (f: Film, lang: "cs" | "en" = "cs") => f.title[lang] || f.title.cs || f.title.en;
const filmTag = (ctx: Ctx, f: Film, lang: "cs" | "en" = "cs") => [catName(ctx, f.categoryId, lang), f.year].filter(Boolean).join(" · ");
export const filmHref = (f: Film) => `${FILM_DIR}/${f.id}.html`;

// ---------------------------------------------------------------- head block

type Seo = {
  title: string;
  description: string;
  path: string;
  image: { path: string; w?: number; h?: number };
  type?: string;
  extra?: string[];
};

function seoBlock(ctx: Ctx, seo: Seo): string {
  const url = ctx.siteUrl ? abs(ctx, seo.path === "index.html" ? "" : seo.path) : "";
  const lines = [
    `<title>${esc(seo.title)}</title>`,
    `<meta name="description" content="${esc(seo.description)}">`,
    url && `<link rel="canonical" href="${esc(url)}">`,
    `<meta property="og:type" content="${seo.type ?? "website"}">`,
    `<meta property="og:site_name" content="${SITE_NAME}">`,
    `<meta property="og:locale" content="cs_CZ">`,
    `<meta property="og:locale:alternate" content="en_US">`,
    `<meta property="og:title" content="${esc(seo.title)}">`,
    `<meta property="og:description" content="${esc(seo.description)}">`,
    url && `<meta property="og:url" content="${esc(url)}">`,
    `<meta property="og:image" content="${esc(abs(ctx, seo.image.path))}">`,
    seo.image.w && `<meta property="og:image:width" content="${seo.image.w}">`,
    seo.image.h && `<meta property="og:image:height" content="${seo.image.h}">`,
    `<meta name="twitter:card" content="summary_large_image">`,
    ...(seo.extra ?? []),
  ].filter(Boolean);
  // Cloudflare Web Analytics: cookieless, so no consent banner is needed.
  const token = readSettings().analyticsToken;
  if (token) lines.push(`<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "${token}"}'></script>`);
  return `<!-- SEO:BEGIN (generated by the editor from the page text; edit the text there) -->\n${lines.join("\n")}\n<!-- SEO:END -->`;
}

const SEO_RE = /<!-- SEO:BEGIN[\s\S]*?<!-- SEO:END -->/;

function organization(ctx: Ctx) {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: SITE_NAME,
    ...(ctx.siteUrl && { url: ctx.siteUrl, logo: abs(ctx, "assets/img/logo-cream-full.png") }),
    email: EMAIL,
    slogan: t(ctx, "hero.slogan", "en"),
    address: { "@type": "PostalAddress", addressCountry: "CZ" },
    founder: [
      { "@type": "Person", name: t(ctx, "erik.name"), jobTitle: t(ctx, "erik.role", "en") },
      { "@type": "Person", name: t(ctx, "mariam.name"), jobTitle: t(ctx, "mariam.role", "en") },
    ],
  };
}

const PAGE_KEYS: Record<PageFile, { title: string; desc: string }> = {
  "index.html": { title: "meta.title.home", desc: "meta.desc.home" },
  "about.html": { title: "meta.title.about", desc: "meta.desc.about" },
  "portfolio.html": { title: "meta.title.portfolio", desc: "meta.desc.portfolio" },
  "contact.html": { title: "meta.title.contact", desc: "meta.desc.contact" },
};

function posterImage(f: Film | undefined) {
  return f?.poster ? { path: f.poster } : DEFAULT_SHARE_IMAGE;
}

function updateMainPages(ctx: Ctx) {
  const lead = ctx.published.find((f) => f.featured) ?? ctx.published[0];
  for (const page of HTML_PAGES) {
    let html = readSite(page);
    const keys = PAGE_KEYS[page];
    const block = seoBlock(ctx, {
      title: t(ctx, keys.title),
      description: t(ctx, keys.desc),
      path: page,
      image: page === "portfolio.html" ? posterImage(lead) : DEFAULT_SHARE_IMAGE,
      extra: page === "index.html" ? [`<script type="application/ld+json">${jsonLd(organization(ctx))}</script>`] : [],
    });
    if (!SEO_RE.test(html)) throw new Error(`${page} is missing its <!-- SEO:BEGIN --> … <!-- SEO:END --> block`);
    html = html.replace(SEO_RE, () => block);
    html = html.replace(/(<html[^>]*data-desc-key=")[^"]*(")/, `$1${keys.desc}$2`);
    if (page === "portfolio.html") html = prerenderGrid(ctx, html);
    if (page === "index.html") html = prerenderTeaser(ctx, html, lead);
    if (page === "contact.html") html = setFormEndpoint(html);
    writeIfChanged(page, html);
  }
}

function setFormEndpoint(html: string) {
  const endpoint = readSettings().formEndpoint;
  return html.replace(/(<form class="contact-form")(?: data-endpoint="[^"]*")?/, endpoint ? `$1 data-endpoint="${esc(endpoint)}"` : "$1");
}

// ---------------------------------------------------------------- film grid (Work page)

const PLAY_ICON = `<span class="play-badge" aria-hidden="true"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M8 5v14l11-7z"/></svg></span>`;

// Same markup portfolio-render.js produces, so the page reads correctly
// before (and without) JavaScript, and search engines see the films.
export function reelCard(ctx: Ctx, f: Film, lead: boolean, base = "") {
  const img = f.poster
    ? `<img src="${esc(base + f.poster)}" alt="" width="1920" height="1080" decoding="async"${lead ? "" : ' loading="lazy"'}>`
    : "";
  return `<a class="reel-card${lead ? " is-lead" : ""}" href="${esc(base + filmHref(f))}" data-film-id="${esc(f.id)}"><span class="reel-media">${img}${PLAY_ICON}</span><span class="reel-info"><span class="project-tag">${esc(filmTag(ctx, f))}</span><span class="reel-title">${esc(filmTitle(f))}</span></span></a>`;
}

const GRID_RE = /(<div id="portfolio-projects"[^>]*>)[\s\S]*?(<\/div><!-- \/portfolio-projects -->)/;

function prerenderGrid(ctx: Ctx, html: string) {
  if (!GRID_RE.test(html)) return html;
  const cards = ctx.published.map((f, i) => reelCard(ctx, f, i === 0)).join("\n");
  html = html.replace(GRID_RE, (_m, open: string, close: string) => `${open}\n${cards}\n${close}`);
  // "More on the way" stays visible while the portfolio is still small.
  return html.replace(/(<div class="more-soon")( hidden)?/, ctx.published.length >= 3 ? "$1 hidden" : "$1");
}

function prerenderTeaser(ctx: Ctx, html: string, lead: Film | undefined) {
  if (!lead) return html.replace(/(<section class="section-pad bg-black work-section")(?! hidden)/, "$1 hidden");
  html = html.replace(/(<section class="section-pad bg-black work-section") hidden/, "$1");
  html = html.replace(/(<a class="work-feature" href=")[^"]*(")/, `$1${esc(filmHref(lead))}$2`);
  html = html.replace(/(<a class="work-feature"[\s\S]*?<img src=")[^"]*(" alt=")[^"]*(")/, `$1${esc(lead.poster)}$2${esc(filmTitle(lead))}$3`);
  html = html.replace(/(<span class="work-feature-tag">)[^<]*(<\/span>)/, `$1${esc(filmTag(ctx, lead))}$2`);
  html = html.replace(/(<span class="work-feature-title h2">)[^<]*(<\/span>)/, `$1${esc(filmTitle(lead))}$2`);
  return html;
}

// ---------------------------------------------------------------- generated pages

// Builds a page from the Work page's own markup, so header, footer, scripts
// and cache-bust versions always match the hand-maintained pages exactly.
function fromShell(ctx: Ctx, opts: { base: string; seo: Seo; htmlAttrs: string; main: string; currentNav?: boolean }) {
  let html = readSite("portfolio.html");
  html = html.replace(/<html[^>]*>/, `<html lang="cs" translate="no" ${opts.htmlAttrs}>`);
  html = html.replace(/<head>/, `<head>\n<base href="${esc(opts.base)}">`);
  html = html.replace(SEO_RE, () => seoBlock(ctx, opts.seo));
  html = html.replace(/<main id="main">[\s\S]*<\/main>/, () => `<main id="main">\n${opts.main}\n</main>`);
  if (!opts.currentNav) html = html.replace(/ aria-current="page"/g, "");
  return html;
}

function filmPage(ctx: Ctx, f: Film, next: Film | undefined) {
  const title = filmTitle(f);
  const media = f.video
    ? `<video controls playsinline preload="metadata"${f.poster ? ` poster="${esc(f.poster)}"` : ""}><source src="${esc(f.video)}" type="video/mp4"></video>`
    : f.poster
      ? `<img src="${esc(f.poster)}" alt="${esc(title)}" width="1920" height="1080">`
      : "";
  const facts = [
    ["film.year", f.year ? String(f.year) : "", "year"],
    ["film.client", f.client, "client"],
  ]
    .filter(([, v]) => v)
    .map(([k, v, field]) => `<div><dt data-i18n="${k}">${esc(t(ctx, k))}</dt><dd data-film-field="${field}">${esc(v)}</dd></div>`)
    .join("");
  const nextBlock = next
    ? `
  <section class="film-next bg-black">
    <div class="container">
      <a class="film-next-link" href="${esc(filmHref(next))}">
        <span class="label" data-i18n="film.next">${esc(t(ctx, "film.next"))}</span>
        <span class="film-next-title h2">${esc(filmTitle(next))}</span>
        <span class="arrow-circle" aria-hidden="true"><svg viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 7h11M7 1l6 6-6 6"/></svg></span>
      </a>
    </div>
  </section>`
    : "";

  const main = `
  <article class="film" data-film-id="${esc(f.id)}">
    <header class="film-head">
      <div class="container">
        <a class="film-back" href="portfolio.html"><svg viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M13 7H2M7 1 1 7l6 6"/></svg><span data-i18n="film.back">${esc(t(ctx, "film.back"))}</span></a>
        <span class="project-tag" data-film-field="tag">${esc(filmTag(ctx, f))}</span>
        <h1 class="film-title" data-film-field="title">${esc(title)}</h1>
      </div>
    </header>
    <div class="film-stage">
      <div class="container">${media}</div>
    </div>
    <div class="film-body">
      <div class="container film-body-grid">
        <p class="lead" data-film-field="description">${esc(f.description.cs)}</p>
        ${facts ? `<dl class="film-facts">${facts}</dl>` : ""}
      </div>
    </div>
  </article>${nextBlock}

  <section class="section-pad bg-cream-2 contact-cta">
    <div class="container">
      <h2 data-i18n="cta.heading">${esc(t(ctx, "cta.heading"))}</h2>
      <p class="lede" data-i18n="cta.body">${esc(t(ctx, "cta.body"))}</p>
      <div class="cta-row">
        <a class="btn btn-solid" href="contact.html" data-i18n="cta.button">${esc(t(ctx, "cta.button"))}</a>
      </div>
    </div>
  </section>`;

  const video =
    ctx.siteUrl && f.video
      ? [
          `<meta property="og:video" content="${esc(abs(ctx, f.video))}">`,
          `<meta property="og:video:type" content="video/mp4">`,
          `<script type="application/ld+json">${jsonLd({
            "@context": "https://schema.org",
            "@type": "VideoObject",
            name: title,
            description: f.description.cs || title,
            thumbnailUrl: f.poster ? abs(ctx, f.poster) : undefined,
            contentUrl: abs(ctx, f.video),
            uploadDate: f.updatedAt.slice(0, 10),
            creator: { "@type": "Organization", name: SITE_NAME },
          })}</script>`,
        ]
      : [];

  return fromShell(ctx, {
    base: "../",
    htmlAttrs: `data-film="${esc(f.id)}"`,
    currentNav: true,
    seo: {
      title: `${title} | ${SITE_NAME}`,
      description: f.description.cs || filmTag(ctx, f) || t(ctx, "meta.desc.portfolio"),
      path: filmHref(f),
      image: posterImage(f),
      type: f.video ? "video.other" : "website",
      extra: video,
    },
    main,
  });
}

function notFoundPage(ctx: Ctx) {
  const main = `
  <section class="not-found">
    <div class="container">
      <p class="not-found-code" aria-hidden="true">404</p>
      <h1 data-i18n="notfound.heading">${esc(t(ctx, "notfound.heading"))}</h1>
      <p class="lead" data-i18n="notfound.body">${esc(t(ctx, "notfound.body"))}</p>
      <div class="cta-row">
        <a class="btn btn-solid" href="index.html" data-i18n="notfound.home">${esc(t(ctx, "notfound.home"))}</a>
        <a class="link-arrow on-dark" href="portfolio.html"><span data-i18n="notfound.work">${esc(t(ctx, "notfound.work"))}</span><span class="arrow-circle" aria-hidden="true"><svg viewBox="0 0 14 14" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M1 7h11M7 1l6 6-6 6"/></svg></span></a>
      </div>
    </div>
  </section>`;
  // GitHub Pages serves this file at whatever address was missing, however
  // deep, so relative links need an absolute base once the address is known.
  return fromShell(ctx, {
    base: ctx.siteUrl || "./",
    htmlAttrs: `data-title-key="notfound.title" data-desc-key="notfound.body"`,
    seo: { title: t(ctx, "notfound.title"), description: t(ctx, "notfound.body"), path: "404.html", image: DEFAULT_SHARE_IMAGE, extra: [`<meta name="robots" content="noindex">`] },
    main,
  }).replace(/<link rel="canonical"[^>]*>\n?/, "");
}

function writeFilmPages(ctx: Ctx) {
  const wanted = new Set<string>();
  ctx.published.forEach((f, i) => {
    const rel = filmHref(f);
    wanted.add(path.basename(rel));
    const next = ctx.published.length > 1 ? ctx.published[(i + 1) % ctx.published.length] : undefined;
    writeIfChanged(rel, filmPage(ctx, f, next));
  });
  const dir = sitePath(FILM_DIR);
  if (fs.existsSync(dir)) {
    for (const name of fs.readdirSync(dir)) {
      if (name.endsWith(".html") && !wanted.has(name)) fs.rmSync(path.join(dir, name));
    }
  }
}

function writeSitemap(ctx: Ctx) {
  // Both need the real address; without one they'd point search engines nowhere.
  if (!ctx.siteUrl) {
    for (const f of ["sitemap.xml", "robots.txt"]) if (siteExists(f)) fs.rmSync(sitePath(f));
    return;
  }
  const today = new Date().toISOString().slice(0, 10);
  const urls = [
    ...HTML_PAGES.map((p) => ({ loc: abs(ctx, p === "index.html" ? "" : p), lastmod: today })),
    ...ctx.published.map((f) => ({ loc: abs(ctx, filmHref(f)), lastmod: f.updatedAt.slice(0, 10) })),
  ];
  writeIfChanged(
    "sitemap.xml",
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls
      .map((u) => `  <url><loc>${esc(u.loc)}</loc><lastmod>${u.lastmod}</lastmod></url>`)
      .join("\n")}\n</urlset>\n`,
  );
  writeIfChanged("robots.txt", `User-agent: *\nAllow: /\n\nSitemap: ${ctx.siteUrl}sitemap.xml\n`);
}

// A CNAME file is how GitHub Pages is told about a custom domain.
function customDomain() {
  if (!siteExists("CNAME")) return "";
  const host = readSite("CNAME").trim().split(/\s+/)[0];
  return host ? `https://${host}/` : "";
}

// siteUrlOverride: at publish time, the GitHub Pages address can stand in
// until a custom domain is set.
export function regenerate(siteUrlOverride?: string) {
  const data = readPortfolio();
  const ctx: Ctx = {
    strings: readStrings(),
    data,
    siteUrl: readSettings().siteUrl || customDomain() || siteUrlOverride || "",
    published: data.projects.filter((p) => p.status === "published"),
  };
  updateMainPages(ctx);
  writeFilmPages(ctx);
  writeIfChanged("404.html", notFoundPage(ctx));
  writeSitemap(ctx);
}
